### ISSUE TITLE
Tight work

### ISSUE THREAD

**Issue by idkjs** [ac27182/reasonml-examples#11]
Seems like building goes ok.

Typing in a channel name doesnt seem to do anything. Searching for a channel doesnt return a created channel. I am sure I am doing something not right. 

Do you mind sharing some instructions on how to use the project?

Thank you for sharing this.

**Comment by ac27182** [comment]
hey @idkjs,

I'm happy you've found the example useful in some way.

So I just brought the app up then on my local machine, maybe I can give you some more in depth Instructions.

1. bring up a fresh instance of the app using `make up`
2. click the `create new channel` button
3. enter a channel display name called `channel1` in the text area
4. click the create `button`
5. refresh your browser session to confirm that the channel has been saved to redis
6. click on the channel you created
7. type in some arbitrary message in the text area in the bottom right hand side of the screen
8. click the `>>=` send button to send your message into the channel
9. refresh your browser session to confirm that the message has been send into the channel

I hope the above instructions serve you well. (let me know how it goes) 

NB: make sure you run `docker-compose down` to ensure the docker network has been torn down before you bring the app up again

Best Wishes,
Alex

**Comment by idkjs** [comment]
@ac27182 Indeed. This has been very useful to learn from. I should have been refreshing the browser, then.

Thank you for taking the time to share this and for responding.

I will revert with update.

Peace to you.
